### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Mothish97** [thien94/orb_slam3_ros_wrapper#14]
I am getting  "fatal error: sophus/se3.hpp: No such file or directory" when I try to build the package. I am using Noetic with Ubuntu 20. Please provide your insights regarding the issue 

 
![error](https://user-images.githubusercontent.com/86384730/180287305-e26d258e-215b-42ee-ac20-0364089169a6.png)

**Comment by Mothish97** [comment]
sudo apt-get install ros-noetic-sophus

**Comment by dazory** [comment]
Alternatively, add `${ORB_SLAM3_DIR}/Thirdparty/Sophus` into `include_directories` like this:

```
include_directories(
   ${ORB_SLAM3_DIR}
   ${ORB_SLAM3_DIR}/include
   ${ORB_SLAM3_DIR}/include/CameraModels
   ${ORB_SLAM3_DIR}/Thirdparty/Sophus # <--
   ${PROJECT_SOURCE_DIR}/include
   ${EIGEN3_INCLUDE_DIR}
   ${catkin_INCLUDE_DIRS}
   ${Pangolin_INCLUDE_DIRS}
)
```
