### ISSUE TITLE
/usr/include/fmt/core.h:863: undefined reference to `fmt... [SOLVED]

### ISSUE THREAD

**Issue by zoldaten** [thien94/orb_slam3_ros_wrapper#17]
i tried to build ros_wrapper on Raspbian buster raspberry pi  as i already build ORB_SLAM3 there.
but failed with error in header.
suddenly i found how to fix that:
i put to catkin_ws/src/orb_slam3_ros_wrapper/include/common.h:
at start of file:
`#define FMT_HEADER_ONLY`
and then that successfully built.

**Comment by thien94** [comment]
Hi @zoldaten , thank you for the information! It will surely be useful for other people.
