### ISSUE TITLE
Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported

### ISSUE THREAD

**Issue by ToshikiNakamura0412** [thien94/orb_slam3_ros_wrapper#19]
When I run "roslaunch orb_slam3_ros_wrapper euroc_monoimu.launch", this error occurs:
![スクリーンショット 2022-10-28 14 22 46](https://user-images.githubusercontent.com/82020865/198509325-1c6def68-410f-4dfc-9268-a0e964a1397e.png)

The above error occurs when map viewer is started. (Map viewer is not displayed.)
Do you know what's the problem with this?

I can run UZ-SLAMLab/ORB_SLAM3 v1.0-release. (EuRoC Examples and ROS Examples)

Environment
- Ubuntu 20.04
- ROS Noetic 
- OpenCV 4.4.0

**Comment by thien94** [comment]
Hi, perhaps one of the libraries uses gtk 2.0 instead of 3.0 which creates an incompatibility issue (the error)
https://github.com/raulmur/ORB_SLAM2/issues/404  https://github.com/raulmur/ORB_SLAM2/issues/325.
- First, check that gtk3.0 is installed with `sudo apt-get install libgtk-3-dev`
- Then, try recompile ORB-SLAM3 from scratch then recompile the ros wrapper.
Hope this helps.

**Comment by ToshikiNakamura0412** [comment]
I did the following
- Install libgtk-3-dev
- Delete the build directory and recompile ORB-SLAM3
- Delete catkin build related files and recompile row wrapper

But, same error occurs.

![スクリーンショット 2022-10-28 15 11 02](https://user-images.githubusercontent.com/82020865/198521480-fd18f7c8-f689-4962-b889-68ccba9e1a9c.png)
↓
![スクリーンショット 2022-10-28 15 11 44](https://user-images.githubusercontent.com/82020865/198521529-42e8ccd3-2a5c-471e-b684-552702dc1396.png)

**Comment by thien94** [comment]
Most likely it is the same issue as https://github.com/thien94/orb_slam3_ros_wrapper/issues/16. Can you try following the same steps to install OpenCV 4.4.0?

**Comment by ToshikiNakamura0412** [comment]
I also installed according to [Mauhing/ORB_SLAM3/README.md](https://github.com/Mauhing/ORB_SLAM3/blob/master/README.md). 
I changed the cmake options when building OpenCV as #16. Then I recompile ORB-SLAM3 and ros wrapper.
The problem was solved.
Thank you very much for your advice.
