### ISSUE TITLE
where the map saved ?

### ISSUE THREAD

**Issue by zoldaten** [thien94/orb_slam3_ros_wrapper#26]
hello.
i put to EuRoC.yaml the line to save a map:
System.SaveAtlasToFile: "~/home/pi/my_map1"
but i seems i doesnt working.
May be ros_wrapper saves map and trajectory somewhere else ?

**Comment by thien94** [comment]
Hi @zoldaten , ORB-SLAM3 uses the param `System.SaveAtlasToFile` to specify only the name of the file, while the directory to be saved in is the `ROS_HOME` folder (which is `~/.ros` by default).

**Comment by zoldaten** [comment]
thanks for the answer. but cant see anything there - only caches and logs.
 may be i should walk around to make a better map and then press Stop button at GUI ORB_SLAM3 as i do ?
![Screenshot_1](https://user-images.githubusercontent.com/29411817/209294261-19f09578-63a8-4112-9c0a-5cae8bab0f27.jpg)

**Comment by thien94** [comment]
> may be i should walk around to make a better map and then press Stop button at GUI ORB_SLAM3 as i do ?

That's a good idea. For more details, ORB-SLAM3 specifies the path file in this function 
https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/System.cc#L1403-L1443
You can change `pathSaveFileName` to a specific location if necessary.

**Comment by zoldaten** [comment]
ok. got it working. the problem was in node. i used usb_cam node that also work correct. now i move to raspicam-node that lets save a map.
strange effect but work -
![Screenshot_2](https://user-images.githubusercontent.com/29411817/209297945-428b5ed5-c844-4ff1-adb4-97c2d58afec3.jpg)
thanks!
