### ISSUE TITLE
Saving and Loading Map Functionality

### ISSUE THREAD

**Issue by cela-s** [thien94/orb_slam3_ros_wrapper#27]
Thank you for creating this easy to use ROS wrapper.

I'm having difficulties loading maps. When trying to save, I click the stop button on GUI that calls the shutdown function to save the trajectories and save the map as a .osa file in Atlas. This seems to work as when I check the ~/.ros directory the camera trajectory and Key Frame trajectories are saved along with the .osa file, but when I run another session it always creates a new map from scratch and never loads the .osa file.

![altas_parameters](https://user-images.githubusercontent.com/114848331/209409812-461ea63b-ee60-4881-8c27-3e692af3ac2e.png)

![ros_dir](https://user-images.githubusercontent.com/114848331/209410038-d14f37c4-2f92-4416-8783-4cc1295684e2.png)

I get the following two errors:

![error1](https://user-images.githubusercontent.com/114848331/209410431-326f756a-ca82-4bbb-b21b-c21349427aab.png)

![error2](https://user-images.githubusercontent.com/114848331/209410554-7f053f72-c2ef-41c8-b719-0c092ebcbb54.png)

Is anyone else experiencing this issue or is the save/load feature working for you?? If it works for you please let know if you've made any changes to the code. I've also tried not using the wrapper and running ORBSLAM on the terminal but I get the same issue. Thank you in advance.

**Comment by thien94** [comment]
Hi @cela-s , thanks for checking out the package.

The Save/Load map functions of ORB-SLAM3 are known to be unstable. See here for the changes https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/443 (unfortunately I don't remember which ones are the essential parts)
There are some folks that have incorporated the fixes and even improved upon the original, you should check them out as well:
https://github.com/Soldann/MORB_SLAM/issues/5
https://github.com/viamrobotics/ORB_SLAM3/pull/4
