### ISSUE TITLE
Getting the odom, rather than Pose

### ISSUE THREAD

**Issue by rakshith95** [thien94/orb_slam3_ros_wrapper#3]
Hello @thien94 , 
Thank you for this wrapper. How can I get the `mono_inertial_node` to publish `nav_msgs:Odometry` information, which includes the `twist` information in addition to the `Pose` information?

**Comment by thien94** [comment]
Hi @rakshith95 , thank you for the question.

As far as I know, only the pose data are provided by ORB-SLAM3 as it is. After looking into the code, I have a few ideas regarding how to obtain the **linear** velocities. However, how to obtain the **angular** velocities is a mystery to me. Furthermore, the covariance or uncertainty is not computed by ORB-SLAM3 for either pose or velocity. Hence, creating a proper `nav_msgs:Odometry` message is unlikely to be possible unless you figure out the above or accept that the message is incomplete.

Nonetheless, to obtain the velocity my suggestion is:
- Figure out which variable contains the latest velocity and in which frame (global or body), possibly [`mVw`](https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/include/Frame.h#L196) or [`mVelocity`](https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/include/Tracking.h#L322), with the former seems more likely.
- Modify [`Tracking.cc`](https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/Tracking.cc) and [`System.cc`](https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/System.cc) to allow access the the aforementioned variables.
- Modify the ROS wrapper (either this package or the provided example) to obtain the velocities, embed them into the ROS message before publishing.

**Comment by rakshith95** [comment]
Thank you for your response. I will update here, after attempting the above. Closing this now

**Comment by gjcliff** [comment]
mVw is linear velocity for the imu:
```cpp
// Frame.h line 185
    // IMU linear velocity
    Eigen::Vector3f mVw;
```
