### ISSUE TITLE
ROS2 Portability

### ISSUE THREAD

**Issue by javieryu** [thien94/orb_slam3_ros_wrapper#34]
Are there plans to migrate this package to ROS2? I'm hunting for a monocular visual SLAM package that supports ROS2, but haven't found anything that replicates the experience on this package in ROS1.

**Comment by thien94** [comment]
Thanks for the question. I am indeed interested in making a ROS2 version of the wrapper, mainly for learning purposes, but have not gotten around to doing it yet. 

In the meantime, have you checked out these packages? Perhaps they already provide everything you need
- https://github.com/open-shade/orbslam3/tree/main
- https://github.com/alsora/ros2-ORB_SLAM2

**Comment by javieryu** [comment]
Great, I will check that out thanks!
