### ISSUE TITLE
Viewer deactivation

### ISSUE THREAD

**Issue by FPSychotic** [thien94/orb_slam3_ros_wrapper#5]
Hi, need desactivate  the viewer, as it kills my performance and it is running in the companion of a UAV.
I disabled it in the ORB-SLAM3 standalone, recompiled , is effectively it is disabled
I recompiled your wrapper, but the Viewer is still there, I checked the files but nothing looks make reference to the viewer, but I have no programming knowledge.

Cheers and thank you by share, take care

**Comment by AnhTuDo1998** [comment]
Hi, if you still have issue with this, you may define a parameter in the launch file as:
``` <param name="enable_pangolin" type="bool" value="false"/> ```

This should deactivate the viewer (Pangolin only)
