### ISSUE TITLE
world frame

### ISSUE THREAD

**Issue by geturin** [thien94/orb_slam3_ros_wrapper#9]
hello,thank you for your work! 

I think there are some problems in world frame.

ORB_SLAM have multiple map and world frame，
every time it fail to track，it will create a new map，and new world frame ( world1 2 3 4

in there, world frame is only one,
so if fail to track, tf have jump to origin ,
run on the wrong path before ORB_SLAM relocalization and back to world1

have any way to always get world1‘s coordinate ？

**Comment by geturin** [comment]
thank for reply
I couldn't find a similar question,
but it doesn't matter anymore, I realise the best solution is dont let it fial to track

there is another small problem, 
I think path canot transform to any frame other than the world frame
when I change the fixed frame, point cloud can get transform, but path can't

**Comment by thien94** [comment]
Have you also changed the name of `target_frame_name` and `source_frame_name` in the [launch file](https://github.com/thien94/orb_slam3_ros_wrapper/blob/master/launch/orb_slam3_mono_euroc.launch#L18-L23)? You probably have to update it every time the name changes.

**Comment by geturin** [comment]
OK it's worked
